In [1]:
from sklearn.feature_extraction.text import TfidfTransformer

In [2]:
tfidf = TfidfTransformer()

In [15]:
tfidf.get_params()  # norm = 12不太懂啥意思

{'norm': 'l2', 'smooth_idf': True, 'sublinear_tf': False, 'use_idf': True}

In [38]:
#counts = [[1,0,2],[1,2,0]]
counts = [[3,0,1],[2,0,0],[3,0,0],[4,0,0],[3,2,0],[3,0,2]]  # 其内部算法用的是ln而不是log  
a = tfidf.fit_transform(counts).toarray()
a

array([[0.85151335, 0.        , 0.52433293],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.55422893, 0.83236428, 0.        ],
       [0.63035731, 0.        , 0.77630514]])

In [43]:
tfidf.idf_  # 每个特征的权重

array([1.        , 2.25276297, 1.84729786])

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [51]:
corpus = ['This is the first document.',
'This is the second second document.',
'And the third one.',
'Is this the first document?']

In [56]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

In [58]:
X.toarray()

array([[0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674],
       [0.        , 0.27230147, 0.        , 0.27230147, 0.        ,
        0.85322574, 0.22262429, 0.        , 0.27230147],
       [0.55280532, 0.        , 0.        , 0.        , 0.55280532,
        0.        , 0.28847675, 0.55280532, 0.        ],
       [0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674]])

In [59]:
vectorizer.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': None,
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}